[profile.default]
src = 'src'
test = 'test/'
out = 'out'
libs = ['lib']
solc_version = "0.8.27"
optimizer = true
optimizer_runs = 500_000
via-ir = true

[fmt]
line_length = 80
number_underscore = "thousands"
multiline_func_header = "all"
sort_imports = true
contract_new_lines = true
override_spacing = false
wrap_comments = true

[rpc_endpoints]
arbitrum = "${ARBITRUM_RPC}"
base = "${BASE_RPC}"

[etherscan]
arbitrum = { key = "${ARBISCAN_API_KEY}" }
base = { key = "${BASESCAN_API_KEY}" }